[package]
name = "hymt-translate"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hymt-core = { path = "../hymt-core" }
hymt-segment = { path = "../hymt-segment" }
hymt-client = { path = "../hymt-client" }
hymt-cache = { path = "../hymt-cache" }
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
