from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import shlex

from hymt.config import HotConfig


PLUGIN_RELATIVE_PATH = Path(".local") / "share" / "hymt" / "hymt-exec.zsh"


@dataclass(frozen=True)
class InstalledZshPlugin:
    plugin_path: Path
    zshrc_path: Path
    source_line: str
    updated_plugin: bool
    updated_zshrc: bool


def install_zsh_plugin(
    config: HotConfig, *, update: bool = False, home: Path | None = None
) -> InstalledZshPlugin:
    active_home = (home or Path.home()).expanduser()
    plugin_path = active_home / PLUGIN_RELATIVE_PATH
    zshrc_path = active_home / ".zshrc"
    if plugin_path.exists() and not update:
        raise FileExistsError(f"{plugin_path} already exists; re-run with --update")
    plugin_path.parent.mkdir(parents=True, exist_ok=True)
    plugin_path.write_text(
        render_zsh_plugin(config.exec_plugin_blocklist), encoding="utf-8"
    )
    source_line = f"source {shlex.quote(str(plugin_path))}"
    updated_zshrc = _ensure_source_line(zshrc_path, source_line)
    return InstalledZshPlugin(
        plugin_path=plugin_path,
        zshrc_path=zshrc_path,
        source_line=source_line,
        updated_plugin=True,
        updated_zshrc=updated_zshrc,
    )


def render_zsh_plugin(blocklist: tuple[str, ...]) -> str:
    blocklist_entries = "\n".join(
        f"  {shlex.quote(command)}" for command in dict.fromkeys(blocklist)
    )
    return f"""# Generated by hymt exec install. Edit config.toml and re-run with --update.

typeset -ga _hymt_exec_blocklist=(
{blocklist_entries}
)

_hymt_has_agent_env() {{
  [[ -n "${{CLAUDE_CODE:-}}" ]] && return 0
  [[ -n "${{CLAUDE_SESSION_ID:-}}" ]] && return 0
  [[ -n "${{CSA_SESSION_DIR:-}}" ]] && return 0
  [[ -n "${{CSA_SESSION_ID:-}}" ]] && return 0
  [[ -n "${{CODEX_SESSION:-}}" ]] && return 0
  [[ -n "${{CODEX_SESSION_ID:-}}" ]] && return 0
  [[ -n "${{GEMINI_CLI:-}}" ]] && return 0
  [[ -n "${{GEMINI_SESSION_ID:-}}" ]] && return 0
  [[ -n "${{OPENCODE_SESSION:-}}" ]] && return 0
  [[ -n "${{AIDER_SESSION_ID:-}}" ]] && return 0
  [[ -n "${{CURSOR_SESSION_ID:-}}" ]] && return 0
  return 1
}}

_hymt_is_agent_child() {{
  local p=$$
  while (( p > 1 )); do
    local comm="$(< /proc/$p/comm 2>/dev/null)" || return 1
    comm="${{comm:l}}"
    case "$comm" in
      claude|claude-code|csa|codex|gemini-cli|gemini|opencode|aider|cursor|copilot|antigravity-cli)
        return 0 ;;
    esac
    local cmdline="$(tr '\\0' ' ' < /proc/$p/cmdline 2>/dev/null)"
    cmdline="${{cmdline:l}}"
    case "$cmdline" in
      *claude*|*claude-code*|*csa*|*codex*|*gemini-cli*|*gemini*|*opencode*|*aider*|*cursor*|*copilot*|*antigravity-cli*)
        return 0 ;;
    esac
    p=$(awk '/^PPid:/{{print $2}}' /proc/$p/status 2>/dev/null) || return 1
  done
  return 1
}}

_hymt_command_blocked() {{
  local cmd="${{1:t}}"
  local blocked
  for blocked in "${{_hymt_exec_blocklist[@]}}"; do
    [[ "$cmd" == "$blocked" ]] && return 0
  done
  return 1
}}

_hymt_inside_script() {{
  [[ -o interactive ]] || return 0
  [[ "$0" == -* || "${{0:t}}" == "zsh" ]] && return 1
  [[ -n "${{ZSH_EVAL_CONTEXT:-}}" && "$ZSH_EVAL_CONTEXT" == *:file:* ]] && return 0
  return 1
}}

_hymt_exec_safe() {{
  [[ -o interactive ]] || return 1
  [[ -t 1 && -t 2 ]] || return 1
  _hymt_has_agent_env && return 1
  _hymt_is_agent_child && return 1
  _hymt_command_blocked "$1" && return 1
  [[ "${{1:t}}" == "hymt" ]] && return 1
  _hymt_inside_script && return 1
  return 0
}}

# The plugin owns the public t command. Remove a pre-existing alias so zsh
# does not expand it while parsing the function definition.
unalias t 2>/dev/null || true

t() {{
  if (( $# == 0 )); then
    command hymt exec --help
    return
  fi
  if _hymt_exec_safe "$1"; then
    command hymt exec -- "$@"
    return
  fi
  "$@"
}}
"""


def _ensure_source_line(path: Path, source_line: str) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    lines = existing.splitlines()
    if source_line in lines:
        return False
    prefix = "" if not existing or existing.endswith("\n") else "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as zshrc:
        zshrc.write(f"{prefix}{source_line}\n")
    return True
