[package]
name = "hymt-segment"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["tokenizer"]
tokenizer = ["dep:tokenizers", "dep:hf-hub"]

[dependencies]
hymt-core = { path = "../hymt-core" }
anyhow = { workspace = true }
thiserror = { workspace = true }
tokenizers = { version = "0.19", default-features = false, features = ["onig"], optional = true }
hf-hub = { version = "0.3", optional = true }
unicode-segmentation = "1"
